## data source configurations

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/shopping?useUnicode=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5  # the minimum connection number
      maximum-pool-size: 20 # the manxmum connection number
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHakariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

## mybatis related
mybatis:
  type-aliases-package: com.dolare.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # only use for development to print sql statement
## server related

server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

## mybatis mapper related
mapper:
  mapper: com.dolare.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pageHelper:
  helperDialect: mysql
  supportMethodsArguments: true